"""Steam 游戏常用中英名对照表（API 离线时使用）"""
GAME_NAMES = {
    "Resident Evil 2": "生化危机 2 重制版",
    "Resident Evil 3": "生化危机 3 重制版",
    "Resident Evil 4": "生化危机 4 重制版",
    "Resident Evil 7 Biohazard": "生化危机 7",
    "Resident Evil Village": "生化危机 8 村庄",
    "The Forest": "森林",
    "Sons Of The Forest": "森林之子",
    "Grand Theft Auto V Enhanced": "GTA5 增强版",
    "No Man's Sky": "无人深空",
    "Satisfactory": "幸福工厂",
    "Street Fighter™ 6": "街霸 6",
    "TEKKEN 8": "铁拳 8",
    "Kingdom Come: Deliverance II": "天国：拯救 2",
    "End of Zoe": "佐伊的结局",
    "Escape the Backrooms": "逃离后室",
    "Cloudheim": "云之家",
    "Backrooms: Escape Together": "后室：共同逃亡",
    "Monster Hunter Rise + Sunbreak": "怪物猎人崛起 曙光",
    "Monster Hunter Wilds": "怪物猎人 荒野",
    "No Rest for the Wicked": "恶意不息",
    "Spyro™ Reignited Trilogy": "斯派罗烈焰重燃",
    "House Flipper Remastered": "房产达人 重制版",
    "EA SPORTS FC™ 26": "FIFA 26",
}
