# 成就配置：成就ID → 名称/条件描述/奖励类型/奖励数量/隐藏
ACHIEVEMENTS = {
    # === 打卡坚持类（积分奖励） ===
    "streak_3": {
        "name": "小火苗🔥",
        "desc": "连续签到3天",
        "reward_type": "shards",
        "reward_amount": 20,
        "hidden": False,
        "category": "打卡",
    },
    "streak_5": {
        "name": "火苗渐旺🔥🔥",
        "desc": "连续签到5天",
        "reward_type": "shards",
        "reward_amount": 30,
        "hidden": False,
        "category": "打卡",
    },
    "streak_7": {
        "name": "初燃火花🔥🔥🔥",
        "desc": "连续签到7天",
        "reward_type": "shards",
        "reward_amount": 50,
        "hidden": False,
        "category": "打卡",
    },
    "streak_10": {
        "name": "火花闪烁🔥🔥🔥🔥",
        "desc": "连续签到10天",
        "reward_type": "shards",
        "reward_amount": 80,
        "hidden": False,
        "category": "打卡",
    },
    "streak_14": {
        "name": "小火把🔥🔥🔥🔥🔥",
        "desc": "连续签到14天",
        "reward_type": "shards",
        "reward_amount": 100,
        "hidden": False,
        "category": "打卡",
    },
    "streak_21": {
        "name": "火焰渐旺🔥🔥🔥🔥🔥🔥",
        "desc": "连续签到21天",
        "reward_type": "shards",
        "reward_amount": 150,
        "hidden": False,
        "category": "打卡",
    },
    "streak_30": {
        "name": "熊熊烈火🔥🔥🔥🔥🔥🔥🔥",
        "desc": "连续签到30天",
        "reward_type": "shards",
        "reward_amount": 200,
        "hidden": False,
        "category": "打卡",
    },
    "streak_45": {
        "name": "烈火燎原🔥🔥🔥🔥🔥🔥🔥🔥",
        "desc": "连续签到45天",
        "reward_type": "shards",
        "reward_amount": 300,
        "hidden": False,
        "category": "打卡",
    },
    "streak_60": {
        "name": "不灭之火🔥🔥🔥🔥🔥🔥🔥🔥🔥",
        "desc": "连续签到60天",
        "reward_type": "shards",
        "reward_amount": 400,
        "hidden": False,
        "category": "打卡",
    },
    "streak_100": {
        "name": "永恒之火🔥👑",
        "desc": "连续签到100天",
        "reward_type": "shards",
        "reward_amount": 500,
        "hidden": False,
        "category": "打卡",
    },
    # === 存钱类（积分奖励） ===
    "saving_100": {
        "name": "积少成多💰",
        "desc": "累计存款100元",
        "reward_type": "shards",
        "reward_amount": 50,
        "hidden": False,
        "category": "存钱",
    },
    "saving_1000": {
        "name": "储蓄新手💰💰",
        "desc": "累计存款1,000元",
        "reward_type": "shards",
        "reward_amount": 100,
        "hidden": False,
        "category": "存钱",
    },
    "saving_5000": {
        "name": "存钱能手💰💰💰",
        "desc": "累计存款5,000元",
        "reward_type": "shards",
        "reward_amount": 300,
        "hidden": False,
        "category": "存钱",
    },
    "saving_20000": {
        "name": "小金库💰💰💰💰",
        "desc": "累计存款20,000元",
        "reward_type": "shards",
        "reward_amount": 500,
        "hidden": False,
        "category": "存钱",
    },
    "saving_100000": {
        "name": "百万富翁💰💰💰💰💰",
        "desc": "累计存款100,000元",
        "reward_type": "shards",
        "reward_amount": 1000,
        "hidden": False,
        "category": "存钱",
    },
    # === 宠物类（积分奖励） ===
    "first_pet": {
        "name": "初次相遇🐾",
        "desc": "获得第一只宠物",
        "reward_type": "shards",
        "reward_amount": 50,
        "hidden": False,
        "category": "宠物",
    },
    "first_form": {
        "name": "成长蜕变🦋",
        "desc": "解锁第一个新形态",
        "reward_type": "shards",
        "reward_amount": 50,
        "hidden": False,
        "category": "宠物",
    },
    "max_intimacy": {
        "name": "心有灵犀💕",
        "desc": "亲密度达到100",
        "reward_type": "shards",
        "reward_amount": 100,
        "hidden": False,
        "category": "宠物",
    },
    "all_pets": {
        "name": "宠物收藏家🐱",
        "desc": "拥有全部5种宠物",
        "reward_type": "shards",
        "reward_amount": 500,
        "hidden": False,
        "category": "宠物",
    },
    # === 抽卡类（积分奖励） ===
    "gacha_10": {
        "name": "初次尝试🎰",
        "desc": "抽卡10次",
        "reward_type": "shards",
        "reward_amount": 50,
        "hidden": False,
        "category": "抽卡",
    },
    "gacha_100": {
        "name": "抽卡达人🎰🎰",
        "desc": "抽卡100次",
        "reward_type": "shards",
        "reward_amount": 200,
        "hidden": False,
        "category": "抽卡",
    },
    "gacha_1000": {
        "name": "扭蛋之王🎰👑",
        "desc": "抽卡1,000次",
        "reward_type": "shards",
        "reward_amount": 500,
        "hidden": False,
        "category": "抽卡",
    },
    # === 隐藏成就（抽卡券奖励） ===
    "first_ssr": {
        "name": "幸运降临✨",
        "desc": "抽到第一个SSR",
        "reward_type": "tickets",
        "reward_amount": 10,
        "hidden": True,
        "category": "隐藏",
    },
    "first_ssrp": {
        "name": "天选之人🌟",
        "desc": "抽到SSR+",
        "reward_type": "tickets",
        "reward_amount": 20,
        "hidden": True,
        "category": "隐藏",
    },
    "all_pets_collected": {
        "name": "全图鉴收集🏆",
        "desc": "集齐所有宠物",
        "reward_type": "tickets",
        "reward_amount": 50,
        "hidden": True,
        "category": "隐藏",
    },
    "first_bind": {
        "name": "情侣同心💑",
        "desc": "首次绑定伴侣",
        "reward_type": "tickets",
        "reward_amount": 10,
        "hidden": True,
        "category": "隐藏",
    },
    "first_evolve": {
        "name": "进化时刻✨",
        "desc": "首次使用进化道具",
        "reward_type": "tickets",
        "reward_amount": 10,
        "hidden": True,
        "category": "隐藏",
    },
    "streak_recover": {
        "name": "重燃火花🔥",
        "desc": "火花从置灰恢复",
        "reward_type": "tickets",
        "reward_amount": 5,
        "hidden": True,
        "category": "隐藏",
    },
}
